attributes:
  - name: document
    type: dict
    text: Specification of document structure
    attributes:
      - name: substitutions
        type: dict
        text: Global substitutions to be applied to all LaTeX content
      - name: structure
        type: list
        text: Document structure specification as a list of blocks
        attributes:
          - name: unstructured
            type: dict
            text: unstructured block specification
            attributes:
              - name: content
                type: str
                text: literal content of the unstructured text block (if source not given)
              - name: source
                type: str
                text: source file for unstructured content (\input{}) (if content not given)
              - name: substitutions
                type: dict
                text: substitutions to be applied to the LaTeX content in this block
          - name: list
            type: dict
            text: list block specification
            attributes:
              - name: type
                type: str
                text: type of list (enumerate or itemize)
                options:
                  - enumerate
                  - itemize
              - name: items
                type: list
                text: list of items in the enumerate block
                attributes:
                  - name: item
                    type: list
                    text: list of items in the list
                    attributes:
                      - name: itemtype
                        type: str
                        text: type of item (text or question)
                        options:
                          - text
                          - question
                      - name: content
                        type: str
                        text: literal content of the text item (if itemtype is text and source not given)
                      - name: source
                        type: str
                        text: source file for item (if content not given)
                      - name: config
                        type: str
                        text: optional configuration file for question template (processed by pythontex)
                      - name: substitutions
                        type: dict
                        text: substitutions to be applied to the LaTeX content in this item
                      - name: points
                        type: int
                        text: number of points to assign to the item (if it is a question)
      - name: class
        type: dict
        text: document class
        default: 
          classname: autoprob
          options: 
            - 11pt
      - name: preamble_commands
        type: list
        text: additional preamble commands
  - name: build
    type: dict
    text: build specifications
    attributes:
      - name: paths
        type: dict
        text: Allows user to specify paths to external executables and directories
        attributes:
          - name: pythontex
            type: str
            text: Path for pythontex executable
            default:  C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pythontex.exe
          - name: pdflatex
            type: str
            text: Path for pdflatex executable
            default: C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe
          - name: build-dir
            type: str
            text: Path for user's build directory
            default: .\build
      - name: copies
        type: int
        text: number of unique copies to generate
        default: 1
      - name: seed
        type: int
        text: rng seed (optional)
      - name: serials
        type: list
        text: |
          list of individual unique serial numbers; each serial number uniquely 
          determines the content of any customizable items in templates; if unset, 
          these are randomly-generated 8-digit integers
      - name: serial-file
        type: str
        text: name of file containing serial numbers; if DNE, it is written
      - name: solutions
        type: bool
        text: build full solutions for each copy
        default: True
      - name: overwrite
        type: bool
        text: overwrite any existing builds with the same serial number(s)
        default: False
      - name: output-dir
        type: str
        text: directory in which output builds are stored
        default: build
      - name: output-name
        type: str
        text: string prepended to all file names generated
        default: tpdoc
      - name: job-name
        type: str
        text: job name passed to pdflatex (defaults to output-name if not given)
      - name: answer-file
        type: str
        text: name of answer file (tex and pdf)
        default: answerset
      - name: combine
        type: dict
        text: combine all PDFs into a single PDF
        attributes:
          - name: name
            type: str
            text: name of output file to generate
          - name: sort
            type: bool
            text: sort files by name when combining
        