directives:
  - name: paths
    type: dict
    text: Allows user to specify paths to external executables and directories
    directives:
      - name: pythontex
        type: str
        text: Path for pythontex executable
        default:  C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pythontex.exe
      - name: pdflatex
        type: str
        text: Path for pdflatex executable
        default: C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe
      - name: build-dir
        type: str
        text: Path for build directory
        default: .\build
  - name: document
    type: dict
    text: Specification of document structure
    directives:
      - name: type
        type: str
        text: Document type (assignment, exam, plain)
        options:
          - assignment
          - exam
          - plain
        default: plain
      - name: structure
        type: list
        text: Document structure specification
        directives:
          - name: items
            type: list
            text: Item specifications; things that carry points
            directives:
              - name: template
                type: dict
                text: Description of a template for an item
                directives:
                  - name: source
                    type: str
                    text: file name of tex template to include
                  - name: config
                    type: str
                    text: name of YAML config file read during template resolution
                  - name: points
                    type: int
                    text: number of points to assign item
          - name: include
            type: str
            text: raw tex file to include
      - name: class
        type: dict
        text: document class
        default: 
          classname: autoprob
          options: 
            - 12pt
      - name: packages
        type: list
        text: default packages
        default:
          - package_name: geometry
            options: 
              - margins=1in
          - package_name: array
      - name: metadata
        type: dict
        text: Document metadata
        directives:
          - name: Termcode
            type: str
            text: term code
            default: 202425
          - name: Termname
            type: str
            text: term name
            default: Winter 2024-2025
          - name: date
            type: str
            text: date to put on document
            default: UNSET-DATE
          - name: description
            type: str
            text: a descriptive title for the document
            default: UNSET-DESCRIPTION
  - name: build
    type: dict
    text: build specifications
    directives:
      - name: copies
        type: int
        text: number of unique copies to generate
        default: 1
      - name: serials
        type: list
        text: list of individual unique serial numbers; each serial number uniquely determines the content of any customizable items in templates; if unset, these are randomly-generated 8-digit integers
      - name: serial-file
        type: str
        text: name of file containing serial numbers; if DNE, it is written
      - name: solutions
        type: bool
        text: build full solutions for each copy
        default: True
      - name: overwrite
        type: bool
        text: overwrite any existing builds with the same serial number(s)
        default: False
      - name: output-dir
        type: str
        text: directory in which output builds are stored
        default: build
      - name: output-name
        type: str
        text: string prepended to all file names generated
        default: tpdoc