attributes:
  - name: paths
    type: dict
    text: Allows user to specify paths to external executables and directories
    attributes:
      - name: pythontex
        type: str
        text: Path for pythontex executable
        default:  C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pythontex.exe
      - name: pdflatex
        type: str
        text: Path for pdflatex executable
        default: C:\Users\cfa22\AppData\Local\Programs\MiKTeX\miktex\bin\x64\pdflatex.exe
      - name: build-dir
        type: str
        text: Path for build directory
        default: .\build
  - name: document
    type: dict
    text: Specification of document structure
    attributes:
      - name: type
        type: str
        text: Document type (assignment, exam, plain)
        options:
          - assignment
          - exam
          - plain
        default: plain
      - name: structure
        type: list
        text: Document structure specification
        attributes:
          - name: template
            type: dict
            text: template specification
            attributes:
              - name: source
                type: str
                text: name of template file
          - name: items
            type: list
            text: Item specifications; things that carry points
            attributes:
              - name: template
                type: dict
                text: Description of a template for an item
                attributes:
                  - name: source
                    type: str
                    text: file name of tex template to include
                  - name: module
                    type: str
                    text: name of accompanying *.py file that is imported by the pycode env in the template
                  - name: config
                    type: str
                    text: name of YAML config file read during template resolution
                  - name: points
                    type: int
                    text: number of points to assign item
          - name: include
            type: str
            text: raw tex file to include via an input directive
      - name: class
        type: dict
        text: document class
        default: 
          classname: autoprob
          options: 
            - 12pt
      - name: packages
        type: list
        text: default packages
        default:
          - package_name: geometry
            options: 
              - margin=1in
          - package_name: array
          - package_name: fancyhdr
      - name: header_commands
        type: list
        text: default header commands
      - name: metadata
        type: dict
        text: Document metadata
        attributes:
          - name: Instructorname
            type: str
            text: instructor name
            default: Cameron F. Abrams
          - name: Instructoremail
            type: str
            text: instructor email
            default: cfa22@drexel.edu
          - name: Coursename
            type: str
            text: course name
            default: UNSET-COURSENAME
          - name: Departmentname
            type: str
            text: department name
            default: UNSET-DEPARTMENTNAME
          - name: Termcode
            type: str
            text: term code
            default: 202425
          - name: Termname
            type: str
            text: term name
            default: Winter 2024-2025
          - name: date
            type: str
            text: date to put on document
            default: UNSET-DATE
          - name: description
            type: str
            text: a descriptive title for the document
            default: UNSET-DESCRIPTION
          - name: assignment_number
            type: int
            text: the assignment number (only used for doc type assignment)
            default: 1
          - name: message
            type: str
            text: A message for the assignment
  - name: build
    type: dict
    text: build specifications
    attributes:
      - name: copies
        type: int
        text: number of unique copies to generate
        default: 1
      - name: seed
        type: int
        text: rng seed (optional)
      - name: serials
        type: list
        text: list of individual unique serial numbers; each serial number uniquely determines the content of any customizable items in templates; if unset, these are randomly-generated 8-digit integers
      - name: serial-file
        type: str
        text: name of file containing serial numbers; if DNE, it is written
      - name: solutions
        type: bool
        text: build full solutions for each copy
        default: True
      - name: overwrite
        type: bool
        text: overwrite any existing builds with the same serial number(s)
        default: False
      - name: output-dir
        type: str
        text: directory in which output builds are stored
        default: build
      - name: output-name
        type: str
        text: string prepended to all file names generated
        default: tpdoc
      - name: answer-file
        type: str
        text: name of answer file (tex and pdf)
        default: answerset
      - name: combine
        type: dict
        text: combine all PDFs into a single PDF
        attributes:
          - name: name
            type: str
            text: name of output file to generate
          - name: sort
            type: bool
            text: sort files by name when combining
        